### ISSUE TITLE
Would you mind to change your username (devactivity)?

### ISSUE THREAD

**Issue by olegcherev** [devactivity/ulangan-rust#1]
I hope this message finds you well. I noticed that there hasn't been much activity associated with your current GitHub username. Our team is working on developing an app to provide valuable features for both Open Source projects and private repositories, and we would greatly appreciate it if you could consider changing your username, so we can use it for an app. This procedure is quite simple and painless, described [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username#changing-your-username)

As a token of our appreciation, I'd be happy to grant you full and unlimited access to our app for an organization of your choice after app release (in next few months).

Thank you in advance for your understanding and cooperation.
Best regards,
Oleg
P.S. I didn't have a more direct way to contact you than submitting the issue.

**Comment by devactivity** [comment]
Hi Oleg,

I hope this message finds you well. Firstly, I want to express my appreciation for your interest in my GitHub username. It's kind of you to reach out and express your organization to have it.

However, I must kindly decline your request to release my GitHub username. I have a strong attachment to this username, and I plan to continue using it for my online activities. I hope you understand and respect my decision in this matter.

I want to assure you that my current inactivity is due to a personal situation that requires my full attention. I value my online presence and contributions, and I do intend to return to active participation on this account as soon as I am able.

Thank you once again for your understanding, and I wish you all the best in your endeavors and beyond.
Warm regards,
DevActivity
